// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcdflosvqaxjkykgstjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjZGZsb3N2cWF4amt5a2dzdGp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxMjQ4MzIsImV4cCI6MjA1MDcwMDgzMn0.X0d0DG5GbfV4-_SQNPOVGb7y6Fl1WSBy8vPjelrXxxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);